spring.application.name=smart-home-backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=smart_home;encrypt=false
spring.datasource.username=smart_home_login
spring.datasource.password=SmartHome123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl